# Generated by Django 5.1.4 on 2024-12-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_alter_surveyresponse_most_recent_antibiotic_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='blood_donation',
            field=models.BooleanField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='covid_vaccination',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='dairy_consumption',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='hair_loss',
            field=models.BooleanField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='vision_problems',
            field=models.BooleanField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3),
        ),
    ]
